### ISSUE TITLE
Try to start moviegeek

### ISSUE THREAD

**Issue by 9health** [9health/moviegeek#4]
Input
- Azure VM

Running methods
- Check whether Azure VM support docker or not => drop (2022/Dec/13)
  - See #6
- Because docker method is so complicated, try to create a new Azure Linux VM and running it
   - See #7
   - See #8

Output
- Successfully run this repository
  - Click the link below to see moviegeek web app
    - http://ninehealth.westus.cloudapp.azure.com:8080
  - Movies and images while setup the web app
     - https://github.com/9health/moviegeek/wiki/res/Screen_Recording_2022-12-14_at_10.14.45.mov
     - https://github.com/9health/moviegeek/wiki/res/Screen_Recording_2022-12-14_at_11.27.48.mov
     - https://github.com/9health/moviegeek/wiki/res/Screenshot_Network_Speed_20221215.heic
     - https://github.com/9health/moviegeek/wiki/res/Screenshot_Network_Speed_20221215A.heic

Risk analysis
- By using second method, the Azure free Linux VM has only 1GB RAM, 600 MB free after booting up. _Hope that it is enough to run `moviegeek` web app!_

Changelog
- 2022/Dec/14: Drop container method, try running it in local Python virtual environment. Add risk analysis.
- 2022/Dec/16: Add moviegeek web app link.

**Comment by 9health** [comment]
Hello @quangvv9Life 

Thanks Quang và anh Công hôm trước đã cùng ngồi thảo luận với tớ xem là nên chọn hướng nào triển khai docker, container và khi nào thì xong nhé 😞.

Cảm ơn Quang đã chấp nhận cho tớ đi tiếp theo hướng Azure nhé mặc dù cái Decision Making của tớ có vấn đề thật =.=

Tớ tạo ra 1 trang Wiki ở đây để sau này có cần quyết định cái gì nhìn vào đấy phân tích cho dễ.

- [[01] Decision Making](https://github.com/9health/moviegeek//wiki/[01]-Decision-Making)

Tớ nghĩ khi đi theo hướng triển khai lên Azure thì
- Sẽ có cái lợi là sau này mình cũng làm, chỉ là làm trước hay làm sau thôi như anh Công nói (tớ cũng tìm ra được ý đấy cũng vào hôm đấy rùi hix nhưng chưa viết ra).
- Cái khó khăn là tốn thời gian hơn như Quang bảo là
  - Nếu deploy lên local ở máy ảo Ubuntu mất 1 giờ.
  - Còn làm kiểu đưa lên Azure này mất tận 4 hay 5 giờ hix.

1 lần nữa cảm ơn Quang nhiều 😢.

À sáng nay 5h45 tớ dậy rồi nhưng cục pin con MBP tự dưng giảm xuống `4%`. Mà rõ ràng qua tớ dùng còn `10%` hay `20%`. Tớ hốt quá liền kiểm tra lại pin ngay phát hiện ra `Maximum Capacity` là `93%` Lại lo lắng quá tớ lên mạng đọc lại cho chắc vì cách đây 1 tháng rõ ràng tớ nhớ tớ xem là `99%` mà.

Trên mạng có cái tool là `coconutBattery` có thể lưu lại lịch sử `%` đấy theo ngày nhưng mất phí. Thế là tớ mò mẫm tìm command line rồi setup `crontab` để hàng ngày chạy lúc `10:10` lưu lại cái `Maximum Capacity `. Thế là toi mất `2h` luôn hix.

Hôm nay tớ sẽ shift session `2h` buổi sáng sang buổi chiều vậy hix hix.

Script tớ làm ở [đây](https://gist.github.com/kid1412-net/b10117919b3861e9c7755a6d59f5410c) hix hix.

Note:
- 2022/Dec/14: Change relative path to absolute path.

**Comment by quangvv9Life** [comment]
Hi Hải,

Tớ nghĩ deploy sẽ chia ra 2 bước chạy song song,  có thể là :
1. Chạy trên server on-prem để tận dụng tốc độ và chi phí : chỉ tốn tiền điện và tk thời gian tìm hiểu thêm về RS thay vì bị mất tập trung tìm hiểu cả về azure
2. Sau kho chạy đc on prem rồi thì chạy trên cloud nhưng sử dụng tk free ở ngoài đã.
 Để tk chi phí cloud để sử dụng toàn bộ $150k cho gđ production vì production rất tốn kém.
 Và ngoài ra còn tk cho phần cognitive service sau này

Vì gđ dev cần chọc ngoáy nhiều nên tớ muốn tk tối đa chi phí cloud cho production. Mà 2 con server ở nhà còn rất nhiều tài nguyên và free !!!

Mình cần tối ưu toàn bộ nguồn lực gđ dev và sử dụng cho prod hoặc sử dụng cho những dịch vụ cần thiết core features như computer vision, speech to text hay ML 

Br
Quang

**Comment by 9health** [comment]
Thanks @quangvv9Life  đã comment nhé 😟 .

Tớ update thêm `Price` vào file [[01] Decision Making](..//wiki/[01]-Decision-Making) ở trong Wiki kia hix.

**Comment by quangvv9Life** [comment]
T vừa cài github app. Check và comment dễ hơn k cần qua email nữa

**Comment by quangvv9Life** [comment]
K hiểu sao k vào đc phần decision making

**Comment by 9health** [comment]
Hello @quangvv9Life 

> T vừa cài github app. Check và comment dễ hơn k cần qua email nữa
,
Cảm ơn Quang suggest @@.

Uhm tớ thấy cái này cũng lạ đời thật.

Lúc được mention kiểu @ thì về mỗi email. Vào GitHub.com chả thấy gì cả =.= Ảo ghê.

**Comment by 9health** [comment]
> K hiểu sao k vào đc phần decision making

@quangvv9Life,

Uhm cảm ơn Quang đã comment.

Tớ chuyển theo kiểu từ đường dẫn tuyệt đối sang tương đối thì okay =.=

```
- [[01] Decision Making](..//wiki/[01]-Decision-Making)
```

to

```
- [[01] Decision Making](https://github.com/9health/moviegeek//wiki/[01]-Decision-Making
```

Nguyên nhân là vì nếu click từ 

https://github.com/9health/moviegeek/issues

Thì sẽ okay..

Còn nếu click từ

https://github.com/9health/moviegeek/projects

Thì sẽ không được.

Nếu dùng kiểu đường dẫn tương đối (relative path).

Có vẻ như GitHub họ để Project là có thể link tới nhiều repositories thì phải =.= 

Và 1 repository link được nhiều project.

Haizzz.

**Comment by quangvv9Life** [comment]
Hi Hải. Trưa nay gặp tí ở quán cơm nhé

**Comment by 9health** [comment]
Hello @quangvv9Life,

Như tớ đã nói với Quang hôm qua (T3, 13/12/2022) thì tớ đã làm các bước sau

- Thử đọc training của Microsoft về containers ở [đây](https://github.com/9health/moviegeek/wiki/%5B10%5D-Azure-docker-container#42-free-training-from-microsoft). Tớ nhận ra rằng quá là phức tạp và cầu kỳ. Tớ hi vọng việc development thực hiện trên container được nhưng mà quả thật đúng như docker ra đời là để deployment thật là nhanh thôi.

1 ví dụ là như Taiga docker mình deploy mất có vài bước, chắc chưa tới 1 giờ.

Cơ mà nếu làm theo cách truyền thống cài các package Python mà mỗi version Ubuntu lại 1 bản Python nữa. Càng nhiều packages thì lại phải modify lại cho đúng version đấy. Thành ra có khi mất cả buổi hay cả ngày tùy vào skill từng người!!!

- Đọc qua thấy phức tạp quá nên tớ skip luôn kiểu dùng docker. Chuyển ra kiểu setup máy ảo (còn 1 máy Linux B1S free 12 tháng nữa) và setup từ đầu tới cuối luôn! Chắc cũng mất 2 giờ để lựa chọn, kiểm tra.

- Setup xong máy ảo thấy okay rồi thì tớ cài đặt và cũng đang chạy được rồi =.=

```
> python3 populate_moviegeek.py => đang chạy, mất 1 tiếng 30 phút chờ
> python3 populate_ratings.py
```

Quang xem video cửa sổ terminal tớ record lại nè T_T.

https://user-images.githubusercontent.com/106132734/207503630-7b9fa1db-1351-48be-a4e5-fb298fa3f348.mov

Vậy thui thanks Quang đã đọc bài viết!!!

Giờ tớ đi document đã.

Còn sáng nay tớ ngồi thử nốt cho xong cái đấy :(.

Còn cái email hôm qua tớ gửi chắc cũng hơi lung tung 😟.

Chiều tớ còn định giúp bạn tớ vụ kia nữa, xem transaction tứ tung đi đâu 😢. Tạm thời để chuyển sang T5 gặp được không hả Quang 😞.

Cảm ơn @quangvv9Life  nhiều!!!

**Comment by quangvv9Life** [comment]
Hi Hải. 
 
Tớ đọc email hôm qua rồi và hiểu băn khoăn và lo lắng của Hải. Cám ơn Hải đã lo lắng cho tớ và đưa ra lời khuyên và tư vấn để không phải nghỉ việc ở MB nhé. 

Cái này mình đã trao đổi nhiều rồi và tớ cũng không muốn nói lại thêm nữa nhé. Hải cố gắng hiểu xem sao. 

Vấn đề về cổ phần và lương : cái này Hải có thể lựa chọn nhé
1. về cổ phần : mục đích của việc thành lập công ty là để cổ đông :
- cùng chung mục tiêu là giúp công ty phát triển và 
- cùng có trách nhiệm với công ty và sản phẩm

Như tớ là 40% , anh Công 30% và Hải 30%. 

Cổ phần hiểu là cùng đóng góp xây dựng công ty của chung và và chia sẻ lợi ích với công ty vì lợi ích của mình  gắn vs công ty thông qua đống % đó. 

Vậy thì các chi phí của cty như chi phí lương mình sẽ cùng góp vốn và trả lương cho tất cả. Nhưng tớ và anh Công sẽ chỉ lấy cổ phần và không lấy lương nên vốn sẽ dùng 1 phần trả cho Hải.

Chứ đừng nghĩ mấy cái % này là tượng trưng nhé !!!

2. Về phần lương : tớ đồng ý với phương án trả lương trao tay (giống như chị tâm lý kia đang nhận ở chỗ làm), như sau : 
tớ sẽ trả lương cho Hải dựa theo số giờ và sp đầu ra

Đồng nghĩa về tỷ lệ sở hữu mình cần phải chia lại để đảm bảo anh Công cũng k bị thiệt.  thì theo tớ Hải nhận lương và giảm tỷ lệ xuống để tớ chia cho anh Công. 

Còn vụ nghỉ việc thì tớ quyết định là nghỉ. 

Thành lập công ty và join vào ms4s rồi có phải for fun đâu mà vừa làm 10 tiếng ơ Mb và dành 3-4 tiếng cho business của mình?

Hải suy nghĩ và báo t về chọn cổ phần hay trả lương để t báo a Công và a luật điều chỉnh nhé !!!

Br
Quang

**Comment by 9health** [comment]
Hello @quangvv9Life,

Cảm ơn Quang đã viết chi tiết nhé hix.

Tớ xin lỗi nếu mà có gì không phải nhé nhưng mà nói chung khả năng của tớ cũng chỉ có hạn thôi.

Thời gian cũng có hạn nữa.

Nên tớ chỉ commit đúng thời gian thế thôi.

Mong Quang thông cảm hix.

Còn chốt cứ nhận % Quang nhé.

Cảm ơn Quang!!!

Còn website đã go live ở đây rùi Quang nhé!

http://ninehealth.westus.cloudapp.azure.com:8080/

```
> python3 populate_ratings.py
```

Lệnh này chạy mất hơn 4 tiếng...

Tớ sẽ update tài liệu sau. Next task có lẽ sẽ đọc overview về cái PRS này O_O.

Có lẽ cái này sẽ cho sang status `Review` nữa.

Một lần nữa cảm ơn Quang!

**Comment by quangvv9Life** [comment]
Cám ơn Hải rất nhiều.  Đáng mừng là tớ và Hải đã cải thiện được hơn ngày xưa vụ lên kế hoạch và ước lượng được khối lượng công việc để đóng 1 task nhé. Hy vọng với cơ chế phối hợp agile chia nhỏ các task phù hợp với khối lượng 2 tuần để hoàn thành được Một lần nữa cũng cám ơn Hải đã tham gia công ty cùng tớ và anh Công nhé. Như hôm qua Hải có nói là về sau có công ty thì sẽ không để nhân viên làm việc căng như tớ ở MB, nhưng đây cũng là business của Hải mà vì mình đóng góp vào xây dựng được mục tiêu cho riêng mình (và có cổ phần mà) Vậy là hoàn thành task đó rồi !!! Các task sau thì nên chia nhỏ ra để tránh overload và cảm nhận được “tiến độ” và “sự thỏa mãn” vậy !!! Tớ sẽ share cho anh Công vào xem nữa !!! Vậy hôm nào bố trí 3 a e hẹn đi ăn 1 bữa nhỉ !!! BRQuang Sent from Mail for Windows From: 9healthSent: Wednesday, December 14, 2022 6:43 PMTo: 9health/moviegeekCc: quangvv9Life; MentionSubject: Re: [9health/moviegeek] Try to start moviegeek (Issue #4) Hello @quangvv9Life,Cảm ơn Quang đã viết chi tiết nhé hix.Tớ xin lỗi nếu mà có gì không phải nhé nhưng mà nói chung khả năng của tớ cũng chỉ có hạn thôi.Thời gian cũng có hạn nữa.Nên tớ chỉ commit đúng thời gian thế thôi.Mong Quang thông cảm hix.Còn chốt cứ nhận % Quang nhé.Cảm ơn Quang!!!Còn website đã go live ở đây rùi Quang nhé!http://ninehealth.westus.cloudapp.azure.com:8080/> python3 populate_ratings.py Lệnh này chạy mất hơn 4 tiếng...Tớ sẽ update tài liệu sau. Next task có lẽ sẽ đọc overview về cái PRS này O_O.Có lẽ cái này sẽ cho sang status Review nữa.Một lần nữa cảm ơn Quang!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by 9health** [comment]
Hello @quangvv9Life,

Cảm ơn Quang đã chia sẻ với tó nhé.

# Về task setup Django web app

Nay tớ cũng đã viết xong Wiki cho 2 cái rùi
- #7 
- #8 

Quang rảnh đọc thử xem dễ hiểu không nhé @@.

Nếu muốn vào server thì tớ cũng có hướng dẫn rùi đấy. File `id_rsa_ninehealth_westus` ở trên folder OneDrive hôm trước tớ chỉ Quang đó.

# Về số giờ đã dùng để làm hôm nay @@

![Screenshot_Screen_Time_20221215](https://lh3.googleusercontent.com/pw/AL9nZEXn5xwv01pyLRRFwnCMWYWe7zQVQ1TvoJw4KYIefentMrQGvAmi4c5Rn1LL8O6U5MdTEg7M5MfkQAXoSUGaCJ0SqNK8il4_xeYu5_Wcx4at1G456XvpBGV40zRY2YpA88NPmIMW-BfGZ0abR_BHSKIOGQ=w1472-h1390-no)

Hôm qua thì chắc thức khuya, ngủ muộn 4AM, trưa lại không ngủ được, tối lại ăn muộn nữa do vậy 5h đặt đồng hồ mà 6h30 mới tỉnh được @@.

Mọi hôm thì cứ đúng 5h30 là tỉnh rồi =.= Cơ thể người đúng là cũng có giới hạn thôi :|

Vậy là sáng tớ ngồi được tầm 1 tiếng tới 7h30 thì đi bê loa giúp mẹ.

8h30 ăn xong, 9h15 ngồi vào 1 xíu thì bạn gọi điện vụ tiền mã hóa kia @@. Thế nào mà cái đứa đang dụ dỗ lại đồng ý cho bạn tớ 4,800 U S D T. 4,000 U S D T đang có rồi, giờ nạp thêm 800 U S D T nữa. Rồi nghe đâu cái đứa Hồng Kông đấy còn bay vào SG 2 tuần nữa với bố mẹ để đi chơi và sau đó vào HN để gặp bạn tớ @@. Loằng ngoằng thật hix.

11h15 nói chuyện xong thì lau nhà tới 11h45 rồi cố viết nốt cái #7.

Trưa thì 2h mẹ mới về @@. Ngủ đến 3h. Đi mua gậy cầm cờ dài dài rồi chở loa 4h mới về. Làm linh tinh tới 4h45 mới ngồi vào. @@.

Đắn đo xem có nên viết nốt cái #8 vì dùng quá 2 tiếng rồi =.=

Như hình trên chắc hôm nay tớ dùng 4 tiếng mất rồi haizzz. Chỉ có viết doc thôi.

# Về họp thứ 7

Quang add anh Công vào xem cũng okay thui @@. Sợ anh ý không có thời gian thui.

Cuối tuần hình như T7 mẹ tớ đi đâu đó. Cơ mà có gì tớ join họp online cũng được :|. Quang cứ tạo meeting link đi, tớ sẽ cố gắng thông báo tối T6 hoặc sáng T7...

Nếu mà không được thì tớ đọc meeting minutes vậy O_O.

Cái này làm cũng đơn giản thôi. Quang tạo 1 file PowerPoint trên OneDrive. Quang với anh Công điền vào đấy trước chủ đề cần nói. Nói đến đâu cái gì cần lưu lại thì viết vào đấy =.=

Sau tớ không join được thì sẽ vào đọc thôi @@.

Tuy hơi kiểu làm chậm mạch suy nghĩ đi nhưng mà có lẽ đấy là cách mà cho ra meeting minute nhanh nhất @@. Vừa họp vừa ghi.

1 cách khác nữa tớ nghĩ rồi là voice record hay screen record thì thực ra cuối cùng cũng phải chuyển về dạng văn bản mới dễ trao đổi hix.

Screen record tốt với cả kiểu vào xem tutorial gì ý...

# Các chuyện khác

Về chuyện làm nhiều hay làm ít giờ thì ý của tớ cũng không phải bắt buộc làm ít mà là
- Làm thế nào cho hiệu quả nhất thôi
- Làm nhiều cũng được, làm ít cũng được

Mỗi độ tuổi, mỗi giai đoạn, mỗi gia đình sẽ có 1 nếp sinh hoạt khác nhau T_T.

Bạn nào cần nhiều kinh nghiệm hoặc nhiều tiền thì làm nhiều vẫn okay.

Bạn nào cần nhiều thứ liên quan tới cuộc sống ngoài thôi thì làm ít vẫn okay.

Làm ít nhận lương ít, làm nhiều nhận lương nhiều.

Tất nhiên sẽ có 1 cái model liên quan tới lương và kinh nghiệm nữa. Thường người nào nhiều kinh nghiệm sẽ được trả lương nhiều hơn người chưa có kinh nghiệm =.= Cơ mà tớ thấy cái đấy cũng hơi sao sao ý vì nó hơi mang tính chủ quan =.= Nhỡ nhận ông nào nhiều kinh nghiệm mà vào làm output không hơn được mấy bạn freshers thì cũng hơi dở =.= Vì CV ở Việt Nam nói chung cũng dễ sửa cho đẹp hơn với người Việt Nam hình như ai cũng nói hay =.=

Thôi cái ý tính sau.

Còn 1 cái nữa là tiền cho công ty từ nguồn nào =.= Nghe ở trên lý tưởng thế thôi chứ không có người làm vì dự án to quá hoặc là có khi dự án bé quá 1 số người ngồi ngoài chơi.

Ý là giao việc phù hợp cho từng người để hoàn thành dự án đúng deadline cũng là 1 nghệ thuật (art) =.=

Hình như tớ ý viết khác 1 chút hay thế nào đó cơ nhưng mà giờ tối nghĩa quá =.=

Thôi khi nào có dịp lại bàn. Cái này HR chắc là sẽ hiểu đúng hơn dân kỹ sư như tớ =.=

Cơ mà tóm lại là vẫn xung quanh giờ làm, kinh nghiệm, tiền cho dự án hay công ty. Khớp được hết mấy cái đấy thì mới bền được còn không kiểu gì cũng tới ngày sập hoặc từ từ hoặc rất nhanh hự hự.

# Các chuyện khác nữa

Thì mẹ tớ về nhà lúc 5h hơn rồi lại chuẩn bị đi ra ngoài vì bạn mẹ bằng tuổi mới mất hix.

6h chiều mẹ ra khỏi nhà. Tớ lại có free time rồi @@.

Lại đắn đo tiếp ngồi hoàn thành nốt cái #8 kia hay là chuyển sang việc khác 😞.

Cơ mà thôi đang đà đấy làm nốt T_T.

May quá cuối cùng cũng xong cả theo ý mình nhưng mà mỗi tội quá mất cái đề ra là `2 tiếng/ngày`. Haizzz tạm thế vậy.

8h30 thì mẹ về rồi và đang chuẩn bị ăn trong lúc tớ viết cái comment này @@.

Mọi thứ có vẻ rất là bình yên và rất là okay khi tớ hoàn thành được xong công việc đề ra nhưng bị quá mát vấn đề thời gian.

Chuyện gì sẽ xảy ra đây =.=

- Tớ còn bài tập chị kia là phải lên plan tương lai 5 năm tới thế nào và deadline khi nào 😐. Task đấy khó thật đấy vì bảo tuần sau mình làm gì thì còn có lẽ nói được (cơ mà chưa chắc đúng). Ví dụ như bảo tìm hộ chị ý cái iMovie cho macOS Catalina và cài thì còn ước lượng được hết bao lâu @@. Hix quả là khó.
  - Phải dành nhiều thời gian suy nghĩ, tìm tòi hơn nữa thu 😢.

- Tớ còn cái meeting T5 tuần trước với meeting T3 tuần này mà chưa ghi lại thành file nữa huhu. Định làm hôm nay mà không được rồi...

- Tớ cần email nốt cho bạn kia mấy thứ tớ quên email hôm qua về vụ tiền mã hóa...

Cảm ơn Quang đã đọc đến đây @@.

Sorry Quang tớ chưa đọc cái tin nhắn iMessage 😞. Tin nhắn ở điện thoại đọc rồi nhưng mà đang tập trung viết nên chưa biết trả lời thế nào 😟.

Chúc Quang setup cái Microsoft 365 thành công nhé!!! Tạo domain và apply đúng cái coupon rồi thì tớ có thể support nốt mấy cái khác trong admin center của Microsoft T_____T.

À lan man 1 vài chuyện khác thì cái file ở trên là file `.heic` tớ chụp trên macOS và dung lượng là `89KB`. Upload lên Google Photos thì dung lượng vẫn y thế. Cơ mà tớ dùng link direct kiểu preview ảnh Google và cho vào đây thì bị convert gì đó thành `.png` và dung lượng `350KB` @@. Thật không hiểu nỗi nữa hự, gần `x4` cái dung lượng ảnh gốc rồi...

Về đoạn tính lương thế nào cho đúng ở trên có lẽ nên thêm 1 tham số nữa là đóng góp vào dự án. Ví dụ như là ý kiến người ý mang tính quyết định chẳng hạn @@. Có lẽ thế. Hoặc là ý kiến 1 người fix bug rất là nhanh thì tốt hơn ý kiến 1 người chưa có kinh nghiệm fix bug T_T. Có lẽ thế thôi.

Vậy thui, cảm ơn Quang!!!

À còn chuyện Quang nghĩ thì nghĩ đi nghĩ lại cuối cùng tớ nghĩ cũng ủng hộ thui O_O. Chúc mọi việc sẽ thuận lợi với Quang!!!

**Comment by quangvv9Life** [comment]
Hi Hải, Thank Hải đã viết lại wiki hướng dẫn đầy đủ tất cả các vấn đề cần để chạy được movieGeek nhé. Tớ đọc thấy chia các đầu mục rất rõ ràng và dễ hiểu, nhìn vào có thể follow được ngay để setup và chạy  Tớ cũng ngó qua cái GitHub Kanban và thấy cũng khá rõ rang và đơn giản. Taiga thì bên trong từng sprint cũng là dạng Kanban thôi, nhưng do đặc thù agile nên các task của Kanban sẽ nằm trong 1 sprint 2 tuần và các task này cũng dựa theo bản chất là “hoàn thành được trong thời gian này”. Nói chung là dùng cái gì để quản lý các task cũng được miễn là có được sản phẩm đầu ra thôi  Tớ cũng move cái task trên taiga về “run PRS” thành done rồi !!! Cám ơn Hải rất nhiều !!! Tớ sẽ setup team để mọi người đăng kí và join vào các buổi họp tiếp theo khi Microsoft gửi mail nhé !!! Hiện tại tớ cũng design được gần 10 cái màn hình cho tính năng chính dựa trên PRS rồi. Và sẽ chia sẻ với Hải và anh Công cũng như 1 vài users để lấy thêm feedback để sửa. Concept là đơn giản ít chữ và dễ hiểu dễ sử dụng – dựa theo ui/ux của spotify, google fit , weight watcher và tiktok Ngoài ra cũng đang tìm hiểu thêm về các tạo động lực cho users khi sử dụng  Một lần nữa cám ơn Hải đã giúp tớ hoàn thành task chạy được PRS nhé !!!  Đoạn về lương ở email này tớ cũng chưa hiểu lắm là ntn :-? Hải có thể nói rõ hơn để tớ có phương án phù hợp được không ? BRQuang  Sent from Mail for Windows From: 9healthSent: Thursday, December 15, 2022 8:54 PMTo: 9health/moviegeekCc: quangvv9Life; MentionSubject: Re: [9health/moviegeek] Try to start moviegeek (Issue #4) Hello @quangvv9Life,Cảm ơn Quang đã chia sẻ với tó nhé.Về task setup Django web appNay tớ cũng đã viết xong Wiki cho 2 cái rùi#7#8Quang rảnh đọc thử xem dễ hiểu không nhé @@.Nếu muốn vào server thì tớ cũng có hướng dẫn rùi đấy. File id_rsa_ninehealth_westus ở trên folder OneDrive hôm trước tớ chỉ Quang đó.Về số giờ đã dùng để làm hôm nay @@Hôm qua thì chắc thức khuya, ngủ muộn 4AM, trưa lại không ngủ được, tối lại ăn muộn nữa do vậy 5h đặt đồng hồ mà 6h30 mới tỉnh được @@.Mọi hôm thì cứ đúng 5h30 là tỉnh rồi =.= Cơ thể người đúng là cũng có giới hạn thôi :|Vậy là sáng tớ ngồi được tầm 1 tiếng tới 7h30 thì đi bê loa giúp mẹ.8h30 ăn xong, 9h15 ngồi vào 1 xíu thì bạn gọi điện vụ tiền mã hóa kia @@. Thế nào mà cái đứa đang dụ dỗ lại đồng ý cho bạn tớ 4,800 U S D T. 4,000 U S D T đang có rồi, giờ nạp thêm 800 U S D T nữa. Rồi nghe đâu cái đứa Hồng Kông đấy còn bay vào SG 2 tuần nữa với bố mẹ để đi chơi và sau đó vào HN để gặp bạn tớ @@. Loằng ngoằng thật hix.11h15 nói chuyện xong thì lau nhà tới 11h45 rồi cố viết nốt cái #7.Trưa thì 2h mẹ mới về @@. Ngủ đến 3h. Đi mua gậy cầm cờ dài dài rồi chở loa 4h mới về. Làm linh tinh tới 4h45 mới ngồi vào. @@.Đắn đo xem có nên viết nốt cái #8 vì dùng quá 2 tiếng rồi =.=Như hình trên chắc hôm nay tớ dùng 4 tiếng mất rồi haizzz. Chỉ có viết doc thôi.Về họp thứ 7Quang add anh Công vào xem cũng okay thui @@. Sợ anh ý không có thời gian thui.Cuối tuần hình như T7 mẹ tớ đi đâu đó. Cơ mà có gì tớ join họp online cũng được :|. Quang cứ tạo meeting link đi, tớ sẽ cố gắng thông báo tối T6 hoặc sáng T7...Nếu mà không được thì tớ đọc meeting minutes vậy O_O.Cái này làm cũng đơn giản thôi. Quang tạo 1 file PowerPoint trên OneDrive. Quang với anh Công điền vào đấy trước chủ đề cần nói. Nói đến đâu cái gì cần lưu lại thì viết vào đấy =.=Sau tớ không join được thì sẽ vào đọc thôi @@.Tuy hơi kiểu làm chậm mạch suy nghĩ đi nhưng mà có lẽ đấy là cách mà cho ra meeting minute nhanh nhất @@. Vừa họp vừa ghi.1 cách khác nữa tớ nghĩ rồi là voice record hay screen record thì thực ra cuối cùng cũng phải chuyển về dạng văn bản mới dễ trao đổi hix.Screen record tốt với cả kiểu vào xem tutorial gì ý...Các chuyện khácVề chuyện làm nhiều hay làm ít giờ thì ý của tớ cũng không phải bắt buộc làm ít mà làLàm thế nào cho hiệu quả nhất thôiLàm nhiều cũng được, làm ít cũng đượcMỗi độ tuổi, mỗi giai đoạn, mỗi gia đình sẽ có 1 nếp sinh hoạt khác nhau T_T.Bạn nào cần nhiều kinh nghiệm hoặc nhiều tiền thì làm nhiều vẫn okay.Bạn nào cần nhiều thứ liên quan tới cuộc sống ngoài thôi thì làm ít vẫn okay.Làm ít nhận lương ít, làm nhiều nhận lương nhiều.Tất nhiên sẽ có 1 cái model liên quan tới lương và kinh nghiệm nữa. Thường người nào nhiều kinh nghiệm sẽ được trả lương nhiều hơn người chưa có kinh nghiệm =.= Cơ mà tớ thấy cái đấy cũng hơi sao sao ý vì nó hơi mang tính chủ quan =.= Nhỡ nhận ông nào nhiều kinh nghiệm mà vào làm output không hơn được mấy bạn freshers thì cũng hơi dở =.= Vì CV ở Việt Nam nói chung cũng dễ sửa cho đẹp hơn với người Việt Nam hình như ai cũng nói hay =.=Thôi cái ý tính sau.Còn 1 cái nữa là tiền cho công ty từ nguồn nào =.= Nghe ở trên lý tưởng thế thôi chứ không có người làm vì dự án to quá hoặc là có khi dự án bé quá 1 số người ngồi ngoài chơi.Ý là giao việc phù hợp cho từng người để hoàn thành dự án đúng deadline cũng là 1 nghệ thuật (art) =.=Hình như tớ ý viết khác 1 chút hay thế nào đó cơ nhưng mà giờ tối nghĩa quá =.=Thôi khi nào có dịp lại bàn. Cái này HR chắc là sẽ hiểu đúng hơn dân kỹ sư như tớ =.=Cơ mà tóm lại là vẫn xung quanh giờ làm, kinh nghiệm, tiền cho dự án hay công ty. Khớp được hết mấy cái đấy thì mới bền được còn không kiểu gì cũng tới ngày sập hoặc từ từ hoặc rất nhanh hự hự.Các chuyện khác nữaThì mẹ tớ về nhà lúc 5h hơn rồi lại chuẩn bị đi ra ngoài vì bạn mẹ bằng tuổi mới mất hix.6h chiều mẹ ra khỏi nhà. Tớ lại có free time rồi @@.Lại đắn đo tiếp ngồi hoàn thành nốt cái #8 kia hay là chuyển sang việc khác 😞.Cơ mà thôi đang đà đấy làm nốt T_T.May quá cuối cùng cũng xong cả theo ý mình nhưng mà mỗi tội quá mất cái đề ra là 2 tiếng/ngày. Haizzz tạm thế vậy.8h30 thì mẹ về rồi và đang chuẩn bị ăn trong lúc tớ viết cái comment này @@.Mọi thứ có vẻ rất là bình yên và rất là okay khi tớ hoàn thành được xong công việc đề ra nhưng bị quá mát vấn đề thời gian.Chuyện gì sẽ xảy ra đây =.=Tớ còn bài tập chị kia là phải lên plan tương lai 5 năm tới thế nào và deadline khi nào 😐. Task đấy khó thật đấy vì bảo tuần sau mình làm gì thì còn có lẽ nói được (cơ mà chưa chắc đúng). Ví dụ như bảo tìm hộ chị ý cái iMovie cho macOS Catalina và cài thì còn ước lượng được hết bao lâu @@. Hix quả là khó.Phải dành nhiều thời gian suy nghĩ, tìm tòi hơn nữa thu 😢.Tớ còn cái meeting T5 tuần trước với meeting T3 tuần này mà chưa ghi lại thành file nữa huhu. Định làm hôm nay mà không được rồi...Tớ cần email nốt cho bạn kia mấy thứ tớ quên email hôm qua về vụ tiền mã hóa...Cảm ơn Quang đã đọc đến đây @@.Sorry Quang tớ chưa đọc cái tin nhắn iMessage 😞. Tin nhắn ở điện thoại đọc rồi nhưng mà đang tập trung viết nên chưa biết trả lời thế nào 😟.Chúc Quang setup cái Microsoft 365 thành công nhé!!! Tạo domain và apply đúng cái coupon rồi thì tớ có thể support nốt mấy cái khác trong admin center của Microsoft T_____T.À lan man 1 vài chuyện khác thì cái file ở trên là file .heic tớ chụp trên macOS và dung lượng là 89KB. Upload lên Google Photos thì dung lượng vẫn y thế. Cơ mà tớ dùng link direct kiểu preview ảnh Google và cho vào đây thì bị convert gì đó thành .png và dung lượng 350KB @@. Thật không hiểu nỗi nữa hự, gần x4 cái dung lượng ảnh gốc rồi...Về đoạn tính lương thế nào cho đúng ở trên có lẽ nên thêm 1 tham số nữa là đóng góp vào dự án. Ví dụ như là ý kiến người ý mang tính quyết định chẳng hạn @@. Có lẽ thế. Hoặc là ý kiến 1 người fix bug rất là nhanh thì tốt hơn ý kiến 1 người chưa có kinh nghiệm fix bug T_T. Có lẽ thế thôi.Vậy thui, cảm ơn Quang!!!À còn chuyện Quang nghĩ thì nghĩ đi nghĩ lại cuối cùng tớ nghĩ cũng ủng hộ thui O_O. Chúc mọi việc sẽ thuận lợi với Quang!!!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by 9health** [comment]
Hello @quangvv9Life,

Task này tớ nghĩ cũng được rùi.

Check log các thứ mở issue mới vậy.

Tớ sẽ chuyển sang trạng thái `Done` nhé.

Thanks Quang!!!

**Comment by quangvv9Life** [comment]
Hi @9health 

Task này nếu chưa ảnh hưởng đến việc chạy thì để ưu tiên sau nhé.

Có thể đóng nếu chưa ảnh hưởng gì !!!

Thank Hải !!!

**Comment by 9health** [comment]
Hello @quangvv9Life,

Task này là `Done` rùi mà Quang @@.

Mọi thứ đã làm xong hết với Output đề ra ý Quang =.=

Tớ thấy câu

> Task này nếu chưa ảnh hưởng đến việc chạy thì để ưu tiên sau nhé.

Có lễ nên comment ở 1 task khác thì đúng hơn @@

Thanks Quang!!!
